services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=root:password@tcp(db:3306)/mydatabase
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command: ["-path=/migrations", "-database=mysql://root:password@tcp(db:3306)/mydatabase", "up"]
    
volumes:
  db-data:
